<?php

namespace ShopBundle\Repository;

/**
 * BtwRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BtwRepository extends \Doctrine\ORM\EntityRepository
{
}
