<?php

namespace ShopBundle\Repository;

/**
 * Product_historyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_historyRepository extends \Doctrine\ORM\EntityRepository
{
}
