<?php

namespace ShopBundle\Repository;

/**
 * Staffel_kortingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Staffel_kortingRepository extends \Doctrine\ORM\EntityRepository
{
}
