<?php

namespace ShopBundle\Repository;

/**
 * Staffel_groupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Staffel_groupsRepository extends \Doctrine\ORM\EntityRepository
{
}
